### ISSUE TITLE
Team 28 Review: Introduction & Scope

### ISSUE THREAD

**Issue by abhishekmagdum** [icecap360/DroneCapstone#12]
Great job on your Hazard Analysis! Not too much I can give constructive criticism on, as you guys have done a great job with going into detail. 

If I had to nitpick, I'd say that your introduction should give more details about what your project is. In section 2, it looks like you start defining the scope halfway through. I would move everything before that, into the introduction, which should give you some more space to expand on the scope/purpose.

**Comment by WinnieTrandinh** [comment]
The team believes that the Introduction should be the introduction on the document, not to the product. Product details should then be discussed within the scope definition.

Other product introductions have already been defined within the SRS which is referenced by the HA.
