### ISSUE TITLE
Team 28 Review: Failure Mode and Effect Analysis

### ISSUE THREAD

**Issue by JasonSurendran** [icecap360/DroneCapstone#13]
Overall very strong Hazard Analysis.

For the FMEA Table I would consider providing a legend or explanation to further explain what the severity, occurrence, and detection columns mean. For example, what would differentiate a severity of 4 compared to a 7 (e.g failure causes more danger etc). Similar logic can be applied to the occurrence and detection columns. Does an occurrence value of 4 mean that it occurs double the amount of time a failure with an occurrence value of would?  If not, how does the scale work? Fully fleshing out what the severity, occurrence, and detection values mean can provide additional clarity on the risks.

**Comment by WinnieTrandinh** [comment]
Additional explanation on the scales used has been added.
