### ISSUE TITLE
Team 28 Review: FMEA

### ISSUE THREAD

**Issue by Rolyap-gh** [icecap360/DroneCapstone#14]
The list of Failure Modes is comprehensive, however all of the recognized Failures Modes (apart from H-011) are described as being related to functional issues with drone performance, rather than harm to human involvement with the system (ie. operator, drivers, maintenance staff, etc). I would suggest there be more consideration of how these malfunctions ultimately harm humans or their property.

**Comment by WinnieTrandinh** [comment]
The system environment only consists of the product and the Operator, which is the user. Thus, only that case is considered.
Further interactions with the environment, such as with the drivers and the property, are further specified within the SRS and User Manual.
