### ISSUE TITLE
Team 27 VnV Plan Review: Ambiguity in some test cases

### ISSUE THREAD

**Issue by aggarwal-h** [icecap360/DroneCapstone#16]
Overall, this VnV Plan is very well done!

One issue I noticed is the ambiguity in some of the test cases. For example, for the test case `STC_015`, it states that "keep the drone on the ground several meters away". In this case, you should try to define what "_several meters_" is referring to. A specific value or a range of values would really help in this case.

**Comment by WinnieTrandinh** [comment]
Many test cases have been rewritten, including the one in question.
Ambiguity is also removed with the new test cases.
