### ISSUE TITLE
Team 27 VnV Plan Review: Static Testing

### ISSUE THREAD

**Issue by tevisdoe** [icecap360/DroneCapstone#17]
Like my colleague said, this is a very well done VnV plan, in my opinion, so at this point I'm just looking for minor nitpicks.

I feel like your static testing could be elaborated on more. There's being concise, and then there's not providing enough information. For example, what standards do your code reviews (mentioned in section 4.5) have? Are these code review purely looking for bugs, do they compare the additions to your requirements? I'd like to see a bit more.

Note: It seems you have labels turned off for non-contributors FYI, feel free to add the Team 27 label when you can.

**Comment by WinnieTrandinh** [comment]
Implementation Verification Plan (Section 4.5) is mentioned to compare implementation with FRs via the state machine.
Code reviews and standards are further specified within Section 4.6 and the Development Plan document.
