### ISSUE TITLE
Team 27 VnV Review: Reflection Appendix

### ISSUE THREAD

**Issue by tevisdoe** [icecap360/DroneCapstone#18]
Again, I'm nitpicking here. Bear with me.

I would like a bit more from your reflection appendix. The table formatting is great, but the options you have leaves something to be desired. For example, in our group we have full on paragraphs dedicated to the options our group members can take. I love the variety you guys have in approaches, as you phrase it, but it would be nice if you elaborated on the chosen approach a bit more.

This is the last issue I'm making, but I just wanted to say that I'm very impressed with your documentation overall. Here's hoping you guys have what it takes to bring the project together and bring home the gold at the exhibition, eh?

**Comment by WinnieTrandinh** [comment]
The team feels that the information is better portrayed within table form for conciseness, and specific resources have already been provided.
