### ISSUE TITLE
Team 27 VnV Review: Navigation References

### ISSUE THREAD

**Issue by cbridel** [icecap360/DroneCapstone#19]
As my colleagues mentioned, your VnV plan is very impressive, and the effort you must have put into it really shines through.

A small suggestion, since the documentation is so thorough, sometimes I found it difficult to cross-reference with other documents like the SRS and MIS. It might have been helpful to have more navigation references throughout the VnV plan, maybe even references to specific locations in the other documents if possible.

**Comment by WinnieTrandinh** [comment]
References are already present between docs, but are only functional if the entire docs/ folder is cloned as it relies on relative paths within the project structure.
