### ISSUE TITLE
Team29 Review: SRS Document Performance/Safety Requirement Consideration

### ISSUE THREAD

**Issue by Kabishan** [icecap360/DroneCapstone#2]
@CSchank

A laudable effort on your team's SRS document, as there is great care to mention the minimum and maximum heights in which the drone can operate. 

A performance requirement that your project may benefit from is the maximum distance that the drone can function from the operator. For example, beyond 10 kilometres, the connection may become too weak for the drone to be controlled and the autonomous state may be triggered to return to the operator. This may also prove to be a safety concern if the connection is too weak and the drone plunges to the ground due to the lack of input.

**Comment by WinnieTrandinh** [comment]
A communication lost state has been added to address this concern, and is further developed with the HA.
