### ISSUE TITLE
Team 27 VnV Review: Issue with one of the links

### ISSUE THREAD

**Issue by GilbertCherrie** [icecap360/DroneCapstone#21]
Very well done VnV plan so it was hard to find any issues with it. I did find a minor issue with one of your links. It looks like the "Appendix B: Formal Transition Table" is meant to be a link to your SRS but clicking it does not do anything.

**Comment by WinnieTrandinh** [comment]
Hey Gilbert, thanks for the feedback.
Could you try the hyperlink again if you clone the whole repo? Or at least the SRS file with the same directory structure?
It's trying to link using relative paths so if the SRS file is missing or placed somewhere else, the hyperlink won't work.
Let me know if it still doesn't work.
Thanks!

**Comment by GilbertCherrie** [comment]
Hi @WinnieTrandinh, I tried it again after cloning the repo and it is still not working.

**Comment by WinnieTrandinh** [comment]
Have you tried opening it through Adobe Acrobat Reader?
I believe it doesn't work if it's open in a browser.

**Comment by GilbertCherrie** [comment]
Ok yeah just tried it with Adobe Acrobat Reader and it worked. Thank you.

**Comment by WinnieTrandinh** [comment]
Glad that it's resolved.
Thanks!
I'll leave the issue open for now though.
