### ISSUE TITLE
Team29 Review: SRS Document Purpose Incomplete

### ISSUE THREAD

**Issue by albertzevanescent** [icecap360/DroneCapstone#3]
@CSchank

Section 1.1 mentions drivers using the parking lot data, but this idea isn't mentioned again. The operator is the only one interacting with the system. Do you intend for drivers to have access to the occupancy map? Or are you leaving it up to the operator to communicate with the drivers? If so, you can expand your scope and have additional requirements to facilitate this communication between the operator and drivers.

**Comment by WinnieTrandinh** [comment]
Drivers are not direct users of the product. Reqs are also present to address the impact of the product on the drivers, such as distractions during operation.
How the information is communicated between the operator and the driver are not within scope of the product, and is up to the operator.
