### ISSUE TITLE
Team 26 DesignDoc Review: Module Services

### ISSUE THREAD

**Issue by abrahamtaha1** [icecap360/DroneCapstone#38]
In section 7.4.1 of the MG, the service of the module is presented as sending images to the Drone Camera module. The only secret mentioned here is the algorithm used for visual perception. Another possible secret for this module is the process/algorithm used to send the image.

**Comment by WinnieTrandinh** [comment]
The secrets on image/data sending are covered in Modules 7.2. Module 7.4.1 is purely on the algo.
