### ISSUE TITLE
 Team 26 DesignDoc Review: Tables

### ISSUE THREAD

**Issue by abrahamtaha1** [icecap360/DroneCapstone#39]
Section 6.4 of the Sys Design - Was not able to see the requirements shown in Tables 4 or 5 even after clicking on them. It is known that the requirements link to the SRS document, but it would have been nice to have a short summary of the requirement and how the relevant component meets/achieves that requirement in Tables 4 & 5 instead of having the reader go look for this answer themselves.

**Comment by WinnieTrandinh** [comment]
Hi Abraham, thanks for the feedback.
I think the hyperlinks only work if you open them using Adobe, and you have the same documentation structure as what's on git.
So could you try it again by cloning the repo, or at least the docs/ folder, and reopening the pdf using adobe?
