### ISSUE TITLE
Team29 Review: Reflection details

### ISSUE THREAD

**Issue by davidwyao** [icecap360/DroneCapstone#4]
@CSchank

Very interesting project idea with plenty to design and build.

I'd suggest for future iterations of the reflection that you expand on how individual team members will acquire the skills that you mentioned, like some specific tutorial or educational YouTube channel. In addition, specify which learning approach each team member would most likely pursue.

One aspect of the domain details I may have missed is the drone's aerial design, i.e. how the propellers would be built/designed to provide adequate lift and stability.

**Comment by fzhanna** [comment]
Hyperlinks have been added to each approach for each domain. The drone's aerial design has been reviewed. Thanks for the feedback.
