### ISSUE TITLE
Team 26 DesignDoc Review: Hardware Specifications

### ISSUE THREAD

**Issue by abrahamtaha1** [icecap360/DroneCapstone#40]
Section 9 of the Sys Design - Wanted to know how exactly that the hardware specifications result in certain performances for the drone, for example a certain amount of thrust is needed hence you selected this propellor and motor.

**Comment by WinnieTrandinh** [comment]
General hardware specs were selected based on Table 9. Following the table ensures that there is sufficient power supply, thrust, and mobility of the drone.
