### ISSUE TITLE
Team 25 VnV Report

### ISSUE THREAD

**Issue by ahmed-nazir** [icecap360/DroneCapstone#45]
Great Work! You did a very thorough job of testing and documenting those tests. One suggestion I would make is to separate out the functional and non functional requirements testing in the document, even though the tractability table covers this it would make the document slightly easier to read. Other then that this is a great document.

**Comment by WinnieTrandinh** [comment]
FRs and NFRs were included within the same section since the test cases covered both FRs and NFRs. There are no test cases that test only FRs or NFRs.
