### ISSUE TITLE
Team29 Review: Community impact requirements

### ISSUE THREAD

**Issue by davidwyao** [icecap360/DroneCapstone#5]
@CSchank

I noticed in section 2.3 you mention minimizing the drone's impact on its surroundings from noise pollution and privacy concerns, among others. There is a security requirement to protect privacy, but I'd suggest further clarification on what "external parties" are. Make sure to include any first party privacy measures as well, I wasn't able to find a requirement for minimizing noise from the drone's propellers, which I think may be useful.

**Comment by WinnieTrandinh** [comment]
Definition of 'External Parties' have been added to definitions.
Noise and distractions are addressed within SAFE_001 and SAFE_004.
