### ISSUE TITLE
Team29 Review: Functional requirements

### ISSUE THREAD

**Issue by GaryGong27** [icecap360/DroneCapstone#6]
The TA for this capstone group is: @CSchank

Great job in creating the the context diagram along with clear inputs and outputs variables.
One thing can be improved for the functional requirement section is to try to express these varaibles relations and requirements in terms of  formalized discrete math expressions as stated in the SRS rubrics.

**Comment by WinnieTrandinh** [comment]
Functional requirements have been formalized via a formal state transition table, shown in Appendix B.
