### ISSUE TITLE
Team 29 Review: Documentation Organization

### ISSUE THREAD

**Issue by almen-ng** [icecap360/DroneCapstone#7]
The TA for this capstone group is: @CSchank

Great job in identifying the use of IEEE 1998 template.

In the rubric it states that, on top of identifying the template, the SRS should follow the template and document all changes from the template. By reviewing the SRS and the IEEE 1998 template, it seems like there is some deviation such as:
- 2.5, the heading should be `Assumptions and Dependencies` and dependencies should be listed
- `Standards compliance` all the way to `Portability` should be underneath the section `Design constraints`
If these deviations are intentional, perhaps documenting the changes in your `Overview` section would work.

In addition, the tables that were provided for the SRS or organized very well; however, for Table 59, I noticed that some of the words in the columns are crossing over to other columns.

Finally, since the IEEE template was used, you can add it in the References as well.

**Comment by WinnieTrandinh** [comment]
Changes mentioned regarding the IEEE templates have been made, thanks.
